const express = require('express');
const mongoose = require('mongoose');
const keys = require('./config/keys');
const cookieSession = require('cookie-session');
const passport = require('passport');
//This is an express middleware
const bodyParser = require('body-parser');

//The order the below statements should b ein order. because first we should define schema in User file
//then we create a instance in passport file
require('./models/User');
//to include the passport.js file or to run
require('./services/passport');
//connectiong to mongoose using the URI generated by mongoose
mongoose.connect(keys.mongoURI);
const app = express();
//If any request comes, this middleware will parse the body and assign it to req.body property of incoming objct
app.use(bodyParser.json());
//function, where we pass cookieSession, to that we provide configuration object
//tell express to make use of cookies
app.use(
    cookieSession({
        //cookie to last 30 days
        maxAge : 30 * 24 * 60 * 60 * 1000,
        //key to encrypt our cookie
        keys : [keys.cookieKey]
    })
);
//Telling passport to use cookies to make authentication
app.use(passport.initialize());
//adding user model instance to req object
app.use(passport.session());

//Passes app argument to authRoutes 
//both files export a function, require statement calls function with app.
require('./routes/authRoutes')(app);
require('./routes/billingRoutes')(app);




const PORT = process.env.PORT || 5000;
app.listen(PORT);