const _ = require('lodash');
const {Path} = require('path-parser');
const URL = require('url');
const mongoose = require('mongoose');
const requireLogin = require('../middlewares/requireLogin'); 
const requireCredits = require('../middlewares/requireCredits');
const Mailer = require('../services/Mailer');
const surveyTemplate = require('../services/emailTemplates/surveyTemplate');
//get the mongoose model class to create an instance of a survey
const Survey = mongoose.model('surveys');
//we export the arrow function and wire it up in index.js
//make sure user is loged in(ie, we use middleware) and check for whether user has enough credits
module.exports = app => {
    app.get('/api/surveys', requireLogin, async (req,res) => {
        const surveys = await Survey.find({_user: req.user.id}).select({recipients: false});
        res.send(surveys);
    });
    app.get('/api/surveys/:surveyId/:choice', (req,res) => {
        res.send('Thanks for voting');
    });
    //filtering data from req, only taking url which contains id and ans
    app.post('/api/surveys/webhooks', (req,res) =>{
        const events = _.chain(req.body)
        .map(({email, url}) => {
            const p = new Path('/api/surveys/:surveyId/:choice');
            const match = p.test(URL.parse(url, true).pathname);
            if(match){
                return {email, surveyId: match.surveyId, choice: match.choice};
            }
        })
        //for unique event, when user clicks multiple times
        //removes undefined events
        .compact()
        .uniqBy('email', 'surveyId')
        .each( ({surveyId, email, choice}) => {
            Survey.updateOne({
                _id: surveyId,
                recipients:{
                    $elemMatch: {email: email, responded: false}
                }
            }, {
                    $inc : {[choice] : 1},
                    $set : {'recipients.$.responded' : true},
                    lastResponded: new Date()
                }
            ).exec();
        })
        .value();

        console.log(events);
        res.send({});
    });
    app.post('/api/surveys', requireLogin,requireCredits, async (req, res) => {
        //client attaches all these attributes to req
        const {title, subject, body, recipients} = req.body;
        const survey = new Survey({
            title,
            subject,
            body,
            //for every email, we return email object with email,
            //map(email => {return {email : email}}) Or
            recipients: recipients.split(',').map((email) => ({email : email.trim()})),
            //this id was automatically generated by mongoose
            _user: req.user.id,
            dateSent : Date.now()
        });
        //send email
        const mailer = new Mailer(survey, surveyTemplate(survey));
        try{
            await mailer.send();
            await survey.save();
            req.user.credits -= 1;
            const user = await req.user.save();
            res.send(user);
        }catch(err){
            res.status(422).send(err);
        }
        
    });
}; 